import Head from "next/head";
import { Container, Card, Row, Text } from "@nextui-org/react";
import Layout from "@/component/Layout/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container xl>
          <Card css={{ $$cardColor: "#ffffff" }}>
            <Card.Body>
              <Row justify="center" align="center">
                <Text h6 size={"$7xl"} color="black" css={{ m: "$4xl" }}>
                  Admin | Dashboard
                </Text>
              </Row>
              <Row justify="center" align="center">
                <Text h6 size={"$xl"} color="black" css={{ m: 0 }}>
                  Selamat Datang
                </Text>
              </Row>
            </Card.Body>
          </Card>
        </Container>
      </Layout>
    </>
  );
}
